### ISSUE TITLE
get_etsy_result failing on url

### ISSUE THREAD

**Issue by mhbw** [alirezamika/tutorials#1]
following the medium tutorial (which is very cool, btw), and my queries all come back with a key error on line 4. example: 

```
def get_etsy_result(search_query):
    url = 'https://www.etsy.com/search?q=%s' % search_query
    result = etsy_scraper.get_result_similar(url, group_by_alias=True)
    result['url'] = [f'https://www.etsy.com/listing/{i}' for i in result['url']]
    return _aggregate_result(result)
  


get_etsy_result('yellow shoes')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in get_etsy_result
KeyError: 'url'

```
any guidance here? seems as though this is the same in each segment.

**Comment by alirezamika** [comment]
Have you fine-tuned the results and see if the urls are being scraped while creating the scraper?

**Comment by mhbw** [comment]
was going down that rabbit hole atm: looks as though my search wasn't
returning anything on etsy hence that first error, that said, now I'm just
getting 404 errors:

example:

`
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
127.0.0.1 - - [05/Jan/2021 12:09:32] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [05/Jan/2021 12:09:32] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [05/Jan/2021 12:11:29] "GET /?q=headphone HTTP/1.1" 404 -
127.0.0.1 - - [05/Jan/2021 12:11:29] "GET /favicon.ico HTTP/1.1" 404 -

`

**Comment by alirezamika** [comment]
Are you using the code of this repository? If not, you probably have some mistake in your url routings.

**Comment by mhbw** [comment]
either this repo or the medium post, yes. 

is there a way to check the routings? what would a successful get look like?

**Comment by alirezamika** [comment]
If you clone this repo and run the server, when you access http://127.0.0.1:8080/?q=headphone via your browser, you won't get any results?

**Comment by mhbw** [comment]
so at first blush, this seemed to work, albeit with very different formatting on the output. still seems like maybe something is off: most are still 404, got one Etsy result. 

 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
127.0.0.1 - - [05/Jan/2021 13:32:15] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [05/Jan/2021 13:32:39] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [05/Jan/2021 13:32:41] "GET /q=headphones HTTP/1.1" 404 -
127.0.0.1 - - [05/Jan/2021 13:32:42] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [05/Jan/2021 13:33:08] "GET /?q=headphone HTTP/1.1" 200 -
127.0.0.1 - - [05/Jan/2021 13:33:08] "GET /favicon.ico HTTP/1.1" 404 -

my goal here is actually to use this to do the same thing on a different site, so I'm less worried about Etsy itself rather than understanding why some of these might be working and others not.

**Comment by alirezamika** [comment]
the only valid request is `GET /?q=headphone` which is ok and you are getting 200.

**Comment by mhbw** [comment]
I guess what I'm getting at (no pun intended) is why does headphone work
and headphones fails, along with everything else?

ideally should be able to take this tutorial and modify to work elsewhere,
no? so I made it for 'yellow corduroy pants' for etsy, which also fails,
etc. what's the change that would make a tutorial like this function more
globally?

**Comment by alirezamika** [comment]
the problem for the `GET /q=headphones` request is that you are not passing `q` as a request parameter. (you are missing `?` before `q`)
